[project]
name = "resistags"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "resistors",
]

[tool.uv.sources]
resistors = { git = "https://github.com/gadhagod/resistors", rev = "master" }
